# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: documentation/requirements.txt

sphinx:
  builder: "mkdocs"
  configuration: documentation/mkdocs.yml
